// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_500 from './routes/_500.tsx';
import * as $_app from './routes/_app.tsx';
import * as $api_joke from './routes/api/joke.ts';
import * as $best_index from './routes/best/index.tsx';
import * as $index from './routes/index.tsx';
import * as $item_id_ from './routes/item/[id].tsx';
import * as $newest_index from './routes/newest/index.tsx';
import * as $Counter from './islands/Counter.tsx';
import type { Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_500.tsx': $_500,
    './routes/_app.tsx': $_app,
    './routes/api/joke.ts': $api_joke,
    './routes/best/index.tsx': $best_index,
    './routes/index.tsx': $index,
    './routes/item/[id].tsx': $item_id_,
    './routes/newest/index.tsx': $newest_index,
  },
  islands: {
    './islands/Counter.tsx': $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
